import { PdfViewer } from "@/components/others";
import Head from "next/head";

const FramerPage = () => {
  const pdfPath = "/pdfs/hooks.pdf";
  return (
    <>
      <Head>
        <title>Venta Única</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Pdf Viewer</h1>
        <PdfViewer pdfPath={pdfPath} />
      </main>
    </>
  );
};

export default FramerPage;
