//*Next
import Head from "next/head";

//*Material UI
import { Box, Card, CardContent, Container, Grid } from "@mui/material";

//*Componentes
import {
  Apellidos,
  Correo,
  Documento,
  Entidad,
  Fecha,
  Identificacion,
  Nombres,
  Persona,
  Respuesta,
  Solicitud,
} from "@/components/type";

import {
  Barrio,
  Comuna,
  Departament,
  Direction,
  Town,
} from "@/components/direction";

import { Boton, Grupo, Politicas, Telefono } from "@/components/others";

export default function Home() {
  return (
    <>
      <Head>
        <title>Venta Única</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Politicas />
        <div>
          <Box my={1}>
            <Container>
              <Card variant="outlined">
                <CardContent>
                  <form>
                    <Grid container direction="row" spacing={2}>
                      <Fecha />
                      <Solicitud />
                      <Persona />
                      <Documento />
                      <Identificacion />
                      <Nombres />
                      <Apellidos />
                      <Entidad />
                      <Respuesta />
                      <Correo />
                      <Departament />
                      <Town />
                      <Comuna />
                      <Barrio />
                      <Direction />
                      <Telefono />
                      <Grupo />
                      <Boton />
                    </Grid>
                  </form>
                </CardContent>
              </Card>
            </Container>
          </Box>
        </div>
      </main>
    </>
  );
}
